[project]
name = "paperman2"
version = "0.1.0"
description = "Paper Manager"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    { name="Doosik Kim" }
]
dependencies = [
  "beautifulsoup4",
  "django",
  "google-genai",
  "openai",
  "pypdf",
  "PyMuPDF"
]
