# Generated by Django 5.1.7 on 2025-03-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
            ],
        ),
    ]
