# Generated by Django 5.1.7 on 2025-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
