# Generated by Django 5.1.7 on 2025-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0002_alter_topic_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
