# Generated by Django 5.1.7 on 2025-03-18 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("author", models.TextField(max_length=80)),
                ("publisher", models.TextField(max_length=80)),
                ("publish_date", models.DateTimeField()),
                ("doi", models.TextField(max_length=80)),
                ("url", models.TextField(max_length=1024)),
                ("pdf_url", models.TextField(max_length=1024)),
                ("pdf_name", models.TextField(max_length=1024)),
                ("citations", models.IntegerField()),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
