# Generated by Django 5.1.7 on 2025-03-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("author", models.CharField(max_length=80)),
                ("publisher", models.CharField(max_length=80)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("doi", models.CharField(max_length=80)),
                ("url", models.URLField(max_length=1024)),
                ("pdf_url", models.URLField(max_length=1024)),
                ("pdf_name", models.CharField(max_length=255)),
                ("citations", models.IntegerField(default=0)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("note", models.TextField(blank=True)),
                (
                    "topics",
                    models.ManyToManyField(related_name="papers", to="topic.topic"),
                ),
            ],
        ),
    ]
