# Generated by Django 5.1.7 on 2025-03-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0002_paper_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="doi",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="paper",
            name="publisher",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
