# Generated by Django 5.1.7 on 2025-03-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0003_alter_paper_doi_alter_paper_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="pdf_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
