# Generated by Django 5.1.7 on 2025-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0004_alter_paper_pdf_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="annotation",
            field=models.TextField(blank=True),
        ),
    ]
