# Generated by Django 5.1.7 on 2025-03-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0005_paper_annotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="abstract",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
