# Generated by Django 5.1.7 on 2025-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0007_alter_paper_citations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="pdf_url",
            field=models.URLField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="paper",
            name="url",
            field=models.URLField(max_length=1024, unique=True),
        ),
    ]
